name: myenvpython37
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.7.2=pyhd8ed1ab_0
  - async_generator=1.10=pyhd8ed1ab_1
  - attrs=24.2.0=pyh71513ae_0
  - brotli-python=1.0.9=py37h0582d14_7
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - django=3.0.6=py_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - freetype=2.10.4=h4cff582_1
  - h11=0.14.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_0
  - jbig=2.1=h0d85af4_2003
  - jpeg=9e=hb7f2c08_3
  - lcms2=2.12=h577c468_0
  - lerc=2.2.1=h046ec9c_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.7=h35c211d_5
  - libffi=3.4.4=hecd8cb5_1
  - libpng=1.6.37=h7cec526_2
  - libtiff=4.3.0=h1167814_1
  - libwebp-base=1.6.0=hb807250_0
  - lz4-c=1.9.3=he49afe7_1
  - mysql-connector-c=6.1.11=hccea1a4_1
  - mysqlclient=1.4.6=py37h0a44026_0
  - ncurses=6.5=h923df54_0
  - olefile=0.47=pyhd8ed1ab_0
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1w=hca72f7f_0
  - outcome=1.3.0.post0=pyhd8ed1ab_0
  - pillow=8.3.2=py37h76dc067_0
  - pip=22.3.1=py37hecd8cb5_0
  - pysocks=1.7.1=py37hf985489_5
  - python=3.7.16=h218abb5_0
  - python_abi=3.7=2_cp37m
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=5.4.1=py37h9ed2024_1
  - readline=8.3=h49f2429_0
  - selenium=4.11.2=pyhd8ed1ab_1
  - selenium-manager=4.11.0=h7205ca4_0
  - setuptools=65.6.3=py37hecd8cb5_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.50.2=hc8b0dd6_1
  - sqlparse=0.4.4=pyhd8ed1ab_0
  - tk=8.6.15=h3a5a201_0
  - trio=0.22.0=py37hf985489_0
  - trio-websocket=0.11.1=pyhd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.38.4=py37hecd8cb5_0
  - wsproto=1.2.0=pyhd8ed1ab_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.0=h582d3a0_0
prefix: /opt/anaconda3/envs/myenvpython37
